// <auto-generated />
using System;
using Medixa_AI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Medixa_AI.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260430194304_AddPasswordHashToEmployee")]
    partial class AddPasswordHashToEmployee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Medixa_AI.Domain.Entities.AIInterpretation", b =>
                {
                    b.Property<Guid>("InterpretationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ResultID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("RiskLevel")
                        .HasColumnType("tinyint");

                    b.Property<int?>("SuggestedSpecializationID")
                        .HasColumnType("int");

                    b.Property<string>("SummaryText")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.HasKey("InterpretationID");

                    b.HasIndex("ResultID")
                        .IsUnique();

                    b.HasIndex("SuggestedSpecializationID");

                    b.ToTable("AIInterpretations");
                });

            modelBuilder.Entity("Medixa_AI.Domain.Entities.Appointment", b =>
                {
                    b.Property<Guid>("AppointmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PatientID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Purpose")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("ReminderSent")
                        .HasColumnType("bit");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("AppointmentID");

                    b.HasIndex("PatientID");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Medixa_AI.Domain.Entities.CheckupRecommendation", b =>
                {
                    b.Property<Guid>("RecommendationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PatientID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateOnly>("SuggestedDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("TestID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RecommendationID");

                    b.HasIndex("PatientID");

                    b.HasIndex("TestID");

                    b.ToTable("CheckupRecommendations");
                });

            modelBuilder.Entity("Medixa_AI.Domain.Entities.Doctor", b =>
                {
                    b.Property<Guid>("DoctorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("ClinicName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SpecializationID")
                        .HasColumnType("int");

                    b.HasKey("DoctorID");

                    b.HasIndex("SpecializationID");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("Medixa_AI.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EmployeeID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Medixa_AI.Domain.Entities.HealthMetricSnapshot", b =>
                {
                    b.Property<Guid>("SnapshotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LastValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("PatientID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TestID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("TrendType")
                        .HasColumnType("tinyint");

                    b.HasKey("SnapshotID");

                    b.HasIndex("PatientID");

                    b.HasIndex("TestID");

                    b.ToTable("HealthMetricSnapshots");
                });

            modelBuilder.Entity("Medixa_AI.Domain.Entities.LabTest", b =>
                {
                    b.Property<Guid>("TestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SampleType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TestID");

                    b.ToTable("LabTests");
                });

            modelBuilder.Entity("Medixa_AI.Domain.Entities.MembershipCategory", b =>
                {
                    b.Property<Guid>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("DiscountPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PointsMultiplier")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("CategoryID");

                    b.ToTable("MembershipCategories");
                });

            modelBuilder.Entity("Medixa_AI.Domain.Entities.OrderDetail", b =>
                {
                    b.Property<Guid>("OrderDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAbnormal")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("TestID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrderDetailID");

                    b.HasIndex("OrderID");

                    b.HasIndex("TestID");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Medixa_AI.Domain.Entities.Patient", b =>
                {
                    b.Property<Guid>("PatientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("BloodType")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte?>("Gender")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NationalID")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PatientID");

                    b.HasIndex("NationalID")
                        .IsUnique();

                    b.HasIndex("Phone");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Medixa_AI.Domain.Entities.PatientMembership", b =>
                {
                    b.Property<Guid>("MembershipID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("CategoryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("PatientID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PointsBalance")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("MembershipID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("PatientID");

                    b.ToTable("PatientMemberships");
                });

            modelBuilder.Entity("Medixa_AI.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("OrderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("PaymentMethod")
                        .HasColumnType("tinyint");

                    b.Property<byte>("PaymentStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PaymentID");

                    b.HasIndex("OrderID")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Medixa_AI.Domain.Entities.Specialization", b =>
                {
                    b.Property<int>("SpecializationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpecializationID"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SpecializationID");

                    b.ToTable("Specializations");
                });

            modelBuilder.Entity("Medixa_AI.Domain.Entities.TestCheckupPolicy", b =>
                {
                    b.Property<Guid>("PolicyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int?>("IsMandatoryForAgeAbove")
                        .HasColumnType("int");

                    b.Property<byte?>("IsMandatoryForGender")
                        .HasColumnType("tinyint");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RecommendedEveryMonths")
                        .HasColumnType("int");

                    b.Property<Guid>("TestID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PolicyID");

                    b.HasIndex("TestID");

                    b.ToTable("TestCheckupPolicies");
                });

            modelBuilder.Entity("Medixa_AI.Domain.Entities.TestMedicalRule", b =>
                {
                    b.Property<Guid>("RuleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("AdviceText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte?>("Gender")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxAge")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("MinAge")
                        .HasColumnType("int");

                    b.Property<decimal>("MinValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<byte>("RiskLevel")
                        .HasColumnType("tinyint");

                    b.Property<int?>("SuggestedSpecializationID")
                        .HasColumnType("int");

                    b.Property<Guid>("TestID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RuleID");

                    b.HasIndex("SuggestedSpecializationID");

                    b.HasIndex("TestID");

                    b.ToTable("TestMedicalRules");
                });

            modelBuilder.Entity("Medixa_AI.Domain.Entities.TestNormalRange", b =>
                {
                    b.Property<Guid>("RangeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<byte?>("Gender")
                        .HasColumnType("tinyint");

                    b.Property<int>("MaxAge")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("MinAge")
                        .HasColumnType("int");

                    b.Property<decimal>("MinValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("TestID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RangeID");

                    b.HasIndex("TestID");

                    b.ToTable("TestNormalRanges");
                });

            modelBuilder.Entity("Medixa_AI.Domain.Entities.TestOrder", b =>
                {
                    b.Property<Guid>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByEmployeeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DoctorID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PatientID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderID");

                    b.HasIndex("CreatedByEmployeeID");

                    b.HasIndex("DoctorID");

                    b.HasIndex("PatientID");

                    b.ToTable("TestOrders");
                });

            modelBuilder.Entity("Medixa_AI.Domain.Entities.TestPrerequisite", b =>
                {
                    b.Property<Guid>("PrerequisiteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FastingHours")
                        .HasColumnType("int");

                    b.Property<string>("InstructionText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("bit");

                    b.Property<Guid>("TestID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PrerequisiteID");

                    b.HasIndex("TestID");

                    b.ToTable("TestPrerequisites");
                });

            modelBuilder.Entity("Medixa_AI.Domain.Entities.TestResult", b =>
                {
                    b.Property<Guid>("ResultID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("OrderDetailID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ResultDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResultText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("ResultValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("TechnicianID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ResultID");

                    b.HasIndex("OrderDetailID")
                        .IsUnique();

                    b.HasIndex("TechnicianID");

                    b.ToTable("TestResults");
                });

            modelBuilder.Entity("Medixa_AI.Domain.Entities.UploadedMedicalFile", b =>
                {
                    b.Property<Guid>("FileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("ExtractedText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("PatientID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Processed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("FileID");

                    b.HasIndex("PatientID");

                    b.ToTable("UploadedMedicalFiles");
                });

            modelBuilder.Entity("Medixa_AI.Domain.Entities.AIInterpretation", b =>
                {
                    b.HasOne("Medixa_AI.Domain.Entities.TestResult", "Result")
                        .WithOne("AIInterpretation")
                        .HasForeignKey("Medixa_AI.Domain.Entities.AIInterpretation", "ResultID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Medixa_AI.Domain.Entities.Specialization", "SuggestedSpecialization")
                        .WithMany("AIInterpretations")
                        .HasForeignKey("SuggestedSpecializationID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Result");

                    b.Navigation("SuggestedSpecialization");
                });

            modelBuilder.Entity("Medixa_AI.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("Medixa_AI.Domain.Entities.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Medixa_AI.Domain.Entities.CheckupRecommendation", b =>
                {
                    b.HasOne("Medixa_AI.Domain.Entities.Patient", "Patient")
                        .WithMany("CheckupRecommendations")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Medixa_AI.Domain.Entities.LabTest", "Test")
                        .WithMany("CheckupRecommendations")
                        .HasForeignKey("TestID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Patient");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("Medixa_AI.Domain.Entities.Doctor", b =>
                {
                    b.HasOne("Medixa_AI.Domain.Entities.Specialization", "Specialization")
                        .WithMany("Doctors")
                        .HasForeignKey("SpecializationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("Medixa_AI.Domain.Entities.HealthMetricSnapshot", b =>
                {
                    b.HasOne("Medixa_AI.Domain.Entities.Patient", "Patient")
                        .WithMany("HealthSnapshots")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Medixa_AI.Domain.Entities.LabTest", "Test")
                        .WithMany("HealthSnapshots")
                        .HasForeignKey("TestID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("Medixa_AI.Domain.Entities.OrderDetail", b =>
                {
                    b.HasOne("Medixa_AI.Domain.Entities.TestOrder", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Medixa_AI.Domain.Entities.LabTest", "Test")
                        .WithMany("OrderDetails")
                        .HasForeignKey("TestID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("Medixa_AI.Domain.Entities.PatientMembership", b =>
                {
                    b.HasOne("Medixa_AI.Domain.Entities.MembershipCategory", "Category")
                        .WithMany("PatientMemberships")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Medixa_AI.Domain.Entities.Patient", "Patient")
                        .WithMany("Memberships")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Medixa_AI.Domain.Entities.Payment", b =>
                {
                    b.HasOne("Medixa_AI.Domain.Entities.TestOrder", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("Medixa_AI.Domain.Entities.Payment", "OrderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Medixa_AI.Domain.Entities.TestCheckupPolicy", b =>
                {
                    b.HasOne("Medixa_AI.Domain.Entities.LabTest", "Test")
                        .WithMany("CheckupPolicies")
                        .HasForeignKey("TestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");
                });

            modelBuilder.Entity("Medixa_AI.Domain.Entities.TestMedicalRule", b =>
                {
                    b.HasOne("Medixa_AI.Domain.Entities.Specialization", "SuggestedSpecialization")
                        .WithMany("MedicalRules")
                        .HasForeignKey("SuggestedSpecializationID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Medixa_AI.Domain.Entities.LabTest", "Test")
                        .WithMany("MedicalRules")
                        .HasForeignKey("TestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SuggestedSpecialization");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("Medixa_AI.Domain.Entities.TestNormalRange", b =>
                {
                    b.HasOne("Medixa_AI.Domain.Entities.LabTest", "Test")
                        .WithMany("NormalRanges")
                        .HasForeignKey("TestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");
                });

            modelBuilder.Entity("Medixa_AI.Domain.Entities.TestOrder", b =>
                {
                    b.HasOne("Medixa_AI.Domain.Entities.Employee", "CreatedByEmployee")
                        .WithMany("CreatedOrders")
                        .HasForeignKey("CreatedByEmployeeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Medixa_AI.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Orders")
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Medixa_AI.Domain.Entities.Patient", "Patient")
                        .WithMany("Orders")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Medixa_AI.Domain.Entities.TestPrerequisite", b =>
                {
                    b.HasOne("Medixa_AI.Domain.Entities.LabTest", "Test")
                        .WithMany("Prerequisites")
                        .HasForeignKey("TestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");
                });

            modelBuilder.Entity("Medixa_AI.Domain.Entities.TestResult", b =>
                {
                    b.HasOne("Medixa_AI.Domain.Entities.OrderDetail", "OrderDetail")
                        .WithOne("Result")
                        .HasForeignKey("Medixa_AI.Domain.Entities.TestResult", "OrderDetailID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Medixa_AI.Domain.Entities.Employee", "Technician")
                        .WithMany("Results")
                        .HasForeignKey("TechnicianID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrderDetail");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("Medixa_AI.Domain.Entities.UploadedMedicalFile", b =>
                {
                    b.HasOne("Medixa_AI.Domain.Entities.Patient", "Patient")
                        .WithMany("UploadedFiles")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Medixa_AI.Domain.Entities.Doctor", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Medixa_AI.Domain.Entities.Employee", b =>
                {
                    b.Navigation("CreatedOrders");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("Medixa_AI.Domain.Entities.LabTest", b =>
                {
                    b.Navigation("CheckupPolicies");

                    b.Navigation("CheckupRecommendations");

                    b.Navigation("HealthSnapshots");

                    b.Navigation("MedicalRules");

                    b.Navigation("NormalRanges");

                    b.Navigation("OrderDetails");

                    b.Navigation("Prerequisites");
                });

            modelBuilder.Entity("Medixa_AI.Domain.Entities.MembershipCategory", b =>
                {
                    b.Navigation("PatientMemberships");
                });

            modelBuilder.Entity("Medixa_AI.Domain.Entities.OrderDetail", b =>
                {
                    b.Navigation("Result");
                });

            modelBuilder.Entity("Medixa_AI.Domain.Entities.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("CheckupRecommendations");

                    b.Navigation("HealthSnapshots");

                    b.Navigation("Memberships");

                    b.Navigation("Orders");

                    b.Navigation("UploadedFiles");
                });

            modelBuilder.Entity("Medixa_AI.Domain.Entities.Specialization", b =>
                {
                    b.Navigation("AIInterpretations");

                    b.Navigation("Doctors");

                    b.Navigation("MedicalRules");
                });

            modelBuilder.Entity("Medixa_AI.Domain.Entities.TestOrder", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Medixa_AI.Domain.Entities.TestResult", b =>
                {
                    b.Navigation("AIInterpretation");
                });
#pragma warning restore 612, 618
        }
    }
}
