// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using patient_lifeCycle.Models;

#nullable disable

namespace patient_lifeCycle.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260430222013_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("patient_lifeCycle.Models.AIInterpretation", b =>
                {
                    b.Property<Guid>("InterpretationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ResultID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SuggestedSpecializationID")
                        .HasColumnType("int");

                    b.Property<string>("SummaryText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("InterpretationID");

                    b.HasIndex("ResultID")
                        .IsUnique();

                    b.HasIndex("SuggestedSpecializationID");

                    b.ToTable("AIInterpretations");
                });

            modelBuilder.Entity("patient_lifeCycle.Models.Appointment", b =>
                {
                    b.Property<Guid>("AppointmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PatientID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Purpose")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("ReminderSent")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AppointmentID");

                    b.HasIndex("PatientID");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("patient_lifeCycle.Models.CheckupRecommendation", b =>
                {
                    b.Property<Guid>("RecommendationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PatientID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("SuggestedDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("TestID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RecommendationID");

                    b.HasIndex("PatientID");

                    b.HasIndex("TestID");

                    b.ToTable("CheckupRecommendations");
                });

            modelBuilder.Entity("patient_lifeCycle.Models.Doctor", b =>
                {
                    b.Property<Guid>("DoctorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClinicName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SpecializationID")
                        .HasColumnType("int");

                    b.HasKey("DoctorID");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("SpecializationID");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("patient_lifeCycle.Models.Employee", b =>
                {
                    b.Property<Guid>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EmployeeID");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("patient_lifeCycle.Models.HealthMetricSnapshot", b =>
                {
                    b.Property<Guid>("SnapshotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LastValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PatientID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TestID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TrendType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SnapshotID");

                    b.HasIndex("PatientID");

                    b.HasIndex("TestID");

                    b.ToTable("HealthMetricSnapshots");
                });

            modelBuilder.Entity("patient_lifeCycle.Models.LabTest", b =>
                {
                    b.Property<Guid>("TestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SampleType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TestID");

                    b.ToTable("LabTests");
                });

            modelBuilder.Entity("patient_lifeCycle.Models.MembershipCategory", b =>
                {
                    b.Property<Guid>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PointsMultiplier")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("CategoryID");

                    b.ToTable("MembershipCategories");
                });

            modelBuilder.Entity("patient_lifeCycle.Models.OrderDetail", b =>
                {
                    b.Property<Guid>("OrderDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAbnormal")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TestID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrderDetailID");

                    b.HasIndex("OrderID");

                    b.HasIndex("TestID");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("patient_lifeCycle.Models.Patient", b =>
                {
                    b.Property<Guid>("PatientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BloodType")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NationalID")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PatientID");

                    b.HasIndex("NationalID")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("patient_lifeCycle.Models.PatientMembership", b =>
                {
                    b.Property<Guid>("MembershipID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("PatientID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PointsBalance")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("MembershipID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("PatientID");

                    b.ToTable("PatientMemberships");
                });

            modelBuilder.Entity("patient_lifeCycle.Models.Payment", b =>
                {
                    b.Property<Guid>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("OrderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PaymentID");

                    b.HasIndex("OrderID")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("patient_lifeCycle.Models.Specialization", b =>
                {
                    b.Property<int>("SpecializationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpecializationID"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SpecializationID");

                    b.ToTable("Specializations");
                });

            modelBuilder.Entity("patient_lifeCycle.Models.TestCheckupPolicy", b =>
                {
                    b.Property<Guid>("PolicyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("IsMandatoryForAgeAbove")
                        .HasColumnType("int");

                    b.Property<string>("IsMandatoryForGender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RecommendedEveryMonths")
                        .HasColumnType("int");

                    b.Property<Guid>("TestID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PolicyID");

                    b.HasIndex("TestID");

                    b.ToTable("TestCheckupPolicies");
                });

            modelBuilder.Entity("patient_lifeCycle.Models.TestMedicalRule", b =>
                {
                    b.Property<Guid>("RuleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdviceText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxAge")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MinAge")
                        .HasColumnType("int");

                    b.Property<decimal>("MinValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SuggestedSpecializationID")
                        .HasColumnType("int");

                    b.Property<Guid>("TestID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RuleID");

                    b.HasIndex("SuggestedSpecializationID");

                    b.HasIndex("TestID");

                    b.ToTable("TestMedicalRules");
                });

            modelBuilder.Entity("patient_lifeCycle.Models.TestNormalRange", b =>
                {
                    b.Property<Guid>("RangeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxAge")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MinAge")
                        .HasColumnType("int");

                    b.Property<decimal>("MinValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("TestID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RangeID");

                    b.HasIndex("TestID");

                    b.ToTable("TestNormalRanges");
                });

            modelBuilder.Entity("patient_lifeCycle.Models.TestOrder", b =>
                {
                    b.Property<Guid>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByEmployeeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DoctorID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PatientID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderID");

                    b.HasIndex("CreatedByEmployeeID");

                    b.HasIndex("DoctorID");

                    b.HasIndex("PatientID");

                    b.ToTable("TestOrders");
                });

            modelBuilder.Entity("patient_lifeCycle.Models.TestPrerequisite", b =>
                {
                    b.Property<Guid>("PrerequisiteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FastingHours")
                        .HasColumnType("int");

                    b.Property<string>("InstructionText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("bit");

                    b.Property<Guid>("TestID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PrerequisiteID");

                    b.HasIndex("TestID");

                    b.ToTable("TestPrerequisites");
                });

            modelBuilder.Entity("patient_lifeCycle.Models.TestResult", b =>
                {
                    b.Property<Guid>("ResultID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("OrderDetailID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ResultDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResultText")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("ResultValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("TechnicianID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ResultID");

                    b.HasIndex("OrderDetailID")
                        .IsUnique();

                    b.HasIndex("TechnicianID");

                    b.ToTable("TestResults");
                });

            modelBuilder.Entity("patient_lifeCycle.Models.UploadedMedicalFile", b =>
                {
                    b.Property<Guid>("FileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExtractedText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("PatientID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Processed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("FileID");

                    b.HasIndex("PatientID");

                    b.ToTable("UploadedMedicalFiles");
                });

            modelBuilder.Entity("patient_lifeCycle.Models.AIInterpretation", b =>
                {
                    b.HasOne("patient_lifeCycle.Models.TestResult", "Result")
                        .WithOne("AIInterpretation")
                        .HasForeignKey("patient_lifeCycle.Models.AIInterpretation", "ResultID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("patient_lifeCycle.Models.Specialization", "SuggestedSpecialization")
                        .WithMany("AIInterpretations")
                        .HasForeignKey("SuggestedSpecializationID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Result");

                    b.Navigation("SuggestedSpecialization");
                });

            modelBuilder.Entity("patient_lifeCycle.Models.Appointment", b =>
                {
                    b.HasOne("patient_lifeCycle.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("patient_lifeCycle.Models.CheckupRecommendation", b =>
                {
                    b.HasOne("patient_lifeCycle.Models.Patient", "Patient")
                        .WithMany("CheckupRecommendations")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("patient_lifeCycle.Models.LabTest", "Test")
                        .WithMany("CheckupRecommendations")
                        .HasForeignKey("TestID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Patient");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("patient_lifeCycle.Models.Doctor", b =>
                {
                    b.HasOne("patient_lifeCycle.Models.Specialization", "Specialization")
                        .WithMany("Doctors")
                        .HasForeignKey("SpecializationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("patient_lifeCycle.Models.HealthMetricSnapshot", b =>
                {
                    b.HasOne("patient_lifeCycle.Models.Patient", "Patient")
                        .WithMany("HealthSnapshots")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("patient_lifeCycle.Models.LabTest", "Test")
                        .WithMany("HealthSnapshots")
                        .HasForeignKey("TestID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("patient_lifeCycle.Models.OrderDetail", b =>
                {
                    b.HasOne("patient_lifeCycle.Models.TestOrder", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("patient_lifeCycle.Models.LabTest", "Test")
                        .WithMany("OrderDetails")
                        .HasForeignKey("TestID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("patient_lifeCycle.Models.PatientMembership", b =>
                {
                    b.HasOne("patient_lifeCycle.Models.MembershipCategory", "Category")
                        .WithMany("PatientMemberships")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("patient_lifeCycle.Models.Patient", "Patient")
                        .WithMany("Memberships")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("patient_lifeCycle.Models.Payment", b =>
                {
                    b.HasOne("patient_lifeCycle.Models.TestOrder", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("patient_lifeCycle.Models.Payment", "OrderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("patient_lifeCycle.Models.TestCheckupPolicy", b =>
                {
                    b.HasOne("patient_lifeCycle.Models.LabTest", "Test")
                        .WithMany("CheckupPolicies")
                        .HasForeignKey("TestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");
                });

            modelBuilder.Entity("patient_lifeCycle.Models.TestMedicalRule", b =>
                {
                    b.HasOne("patient_lifeCycle.Models.Specialization", "SuggestedSpecialization")
                        .WithMany("MedicalRules")
                        .HasForeignKey("SuggestedSpecializationID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("patient_lifeCycle.Models.LabTest", "Test")
                        .WithMany("MedicalRules")
                        .HasForeignKey("TestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SuggestedSpecialization");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("patient_lifeCycle.Models.TestNormalRange", b =>
                {
                    b.HasOne("patient_lifeCycle.Models.LabTest", "Test")
                        .WithMany("NormalRanges")
                        .HasForeignKey("TestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");
                });

            modelBuilder.Entity("patient_lifeCycle.Models.TestOrder", b =>
                {
                    b.HasOne("patient_lifeCycle.Models.Employee", "CreatedByEmployee")
                        .WithMany("CreatedOrders")
                        .HasForeignKey("CreatedByEmployeeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("patient_lifeCycle.Models.Doctor", "Doctor")
                        .WithMany("TestOrders")
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("patient_lifeCycle.Models.Patient", "Patient")
                        .WithMany("Orders")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("patient_lifeCycle.Models.TestPrerequisite", b =>
                {
                    b.HasOne("patient_lifeCycle.Models.LabTest", "Test")
                        .WithMany("Prerequisites")
                        .HasForeignKey("TestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");
                });

            modelBuilder.Entity("patient_lifeCycle.Models.TestResult", b =>
                {
                    b.HasOne("patient_lifeCycle.Models.OrderDetail", "OrderDetail")
                        .WithOne("Result")
                        .HasForeignKey("patient_lifeCycle.Models.TestResult", "OrderDetailID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("patient_lifeCycle.Models.Employee", "Technician")
                        .WithMany("Results")
                        .HasForeignKey("TechnicianID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrderDetail");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("patient_lifeCycle.Models.UploadedMedicalFile", b =>
                {
                    b.HasOne("patient_lifeCycle.Models.Patient", "Patient")
                        .WithMany("UploadedFiles")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("patient_lifeCycle.Models.Doctor", b =>
                {
                    b.Navigation("TestOrders");
                });

            modelBuilder.Entity("patient_lifeCycle.Models.Employee", b =>
                {
                    b.Navigation("CreatedOrders");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("patient_lifeCycle.Models.LabTest", b =>
                {
                    b.Navigation("CheckupPolicies");

                    b.Navigation("CheckupRecommendations");

                    b.Navigation("HealthSnapshots");

                    b.Navigation("MedicalRules");

                    b.Navigation("NormalRanges");

                    b.Navigation("OrderDetails");

                    b.Navigation("Prerequisites");
                });

            modelBuilder.Entity("patient_lifeCycle.Models.MembershipCategory", b =>
                {
                    b.Navigation("PatientMemberships");
                });

            modelBuilder.Entity("patient_lifeCycle.Models.OrderDetail", b =>
                {
                    b.Navigation("Result");
                });

            modelBuilder.Entity("patient_lifeCycle.Models.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("CheckupRecommendations");

                    b.Navigation("HealthSnapshots");

                    b.Navigation("Memberships");

                    b.Navigation("Orders");

                    b.Navigation("UploadedFiles");
                });

            modelBuilder.Entity("patient_lifeCycle.Models.Specialization", b =>
                {
                    b.Navigation("AIInterpretations");

                    b.Navigation("Doctors");

                    b.Navigation("MedicalRules");
                });

            modelBuilder.Entity("patient_lifeCycle.Models.TestOrder", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("patient_lifeCycle.Models.TestResult", b =>
                {
                    b.Navigation("AIInterpretation");
                });
#pragma warning restore 612, 618
        }
    }
}
